version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 0000
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "8080:8080"

volumes:
  mariadb_data: